[pyprland]
plugins = ["scratchpads"]

[workspaces_follow_focus]
max_workspaces = 9

[scratchpads.btm]
command = "kitty --class=\"kitty-btm\" zsh -c \"btm\""
animation = "fromTop"
class = "kitty-btm"
lazy = true
size = "75% 65%"

[scratchpads.spo]
command = "spotube"
animation = "fromTop"
class = "spotube"
lazy = true
size = "80% 80%"

# spotube
# discord
# noogle
# nixkpg-search
# home-manager options search
# lichess

# [scratchpads.jfmp]
# animation = "fromTop"
# command = "jellyfinmediaplayer"
# # class = "org.jellyfin."
# size = "75% 60%"

# [scratchpads.stb-logs]
# animation = "fromTop"
# command = "kitty --class kitty-stb-logs stbLog"
# class = "kitty-stb-logs"
# lazy = true
# size = "75% 40%"
#

# [scratchpads.volume]
# animation = "fromRight"
# command = "pavucontrol"
# class = "pavucontrol"
# lazy = true
# size = "40% 90%"
# unfocus = "hide"
